# Generated by Django 3.2.5 on 2021-08-25 21:12

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('book_image', models.URLField()),
                ('book_name', models.CharField(max_length=100)),
                ('book_author', models.CharField(max_length=100)),
                ('price', models.FloatField()),
                ('genre', models.CharField(choices=[('Architecture', 'Architecture'), ('Bibles', 'Bibles'), ('Computer', 'Computer'), ('Encyclopedia', 'Encyclopedia'), ('History', 'History'), ('Language & Literature', 'Language & Literature'), ('Mathematics', 'Mathematics'), ('Medical', 'Medical'), ('Psychology', 'Psychology'), ('Science', 'Science'), ('Social Science', 'Social Science'), ('Technology & Engineering', 'Technology & Engineering')], max_length=100)),
                ('description', models.TextField()),
                ('quantity', models.PositiveIntegerField()),
                ('book_link', models.URLField(blank=True)),
                ('date_published', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='OwnedBook',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_sold', models.DateTimeField(auto_now_add=True)),
                ('book_sold', models.PositiveIntegerField(default=0)),
                ('owned', models.CharField(choices=[('not owned', 'not owned'), ('owned', 'owned')], default='not owned', max_length=100, null=True)),
                ('book', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='booksforbrain.book')),
                ('reader', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
