# Generated by Django 3.2.5 on 2021-08-25 21:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booksforbrain', '0003_auto_20210825_1414'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='genre',
            field=models.CharField(choices=[('Bibles', 'Bibles'), ('Computer', 'Computer'), ('Encyclopedia', 'Encyclopedia'), ('History', 'History'), ('Language & Literature', 'Language & Literature'), ('Mathematics', 'Mathematics'), ('Medical', 'Medical'), ('Psychology', 'Psychology'), ('Science', 'Science'), ('Social Science', 'Social Science'), ('Technology & Engineering', 'Technology & Engineering')], max_length=100),
        ),
    ]
